### PR TITLE
Save entry list compressed in extension state

### LINKED ISSUE #413: Extension state exceeds the default request size limit of etcd when cluster has > 2000 DNSEntries
**How to categorize this issue?**

/area scalability
/kind enhancement

**What happened**:
Folks conducted a performance test for a Shoot cluster.

They deployed >13,000 DNSEntries as part of the test.

After ~2000 DNSEntries, the `shoot_dns_service_replication_controller` fails to maintain the DNSEntries in the Extension `.status.state.entries` field.
```
{"log":{"controller":"shoot_dns_service_replication_controller","error":"etcdserver: request is too large","level":"error","msg":"Reconciler error","name":"4e8a3eff-e5ad-4604-ba16-7a459bc5b618-app-dnsentry-v88f8","namespace":"shoot--cbc-multi--test-perf","object":{"name":"4e8a3eff-e5ad-4604-ba16-7a459bc5b618-app-dnsentry-v88f8","namespace":"shoot--cbc-multi--test-perf"},"reconcileID":"5340e62d-38f7-4848-bae5-4876857b536b","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224","ts":"2025-01-09T09:40:00.908Z"}}
```

gardenlet cannot update the Extension resource as well as part of the Shoot reconciliation:
```yaml
status:
  lastErrors:
    - description: "task \"Deploying extension resources after kube-apiserver\" failed: retry failed with context deadline exceeded, last error: 1 error occurred:\n\t* etcdserver: request is too large\n\n"
      taskID: Deploying extension resources after kube-apiserver
      lastUpdateTime: '2025-01-09T09:54:54Z'
```

Colleagues shared that every DNSEntry from the Shoot cluster is being maintained in the `.status.state.entries` field of the Extension object. 

We could try to improve by compressing the resources in the Extension state. @plkokanov shared an example where we use compression to store the machine states in the ShootState resource: https://github.com/gardener/gardener/blob/ab8ede5a1f38a643a4ab0d03b8c42d21ee9ef34b/pkg/utils/gardener/shootstate/shootstate.go#L129-L150

**What you expected to happen**:
No `etcdserver: request is too large` error caused when DNSEntries count > 2000.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
N/A

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.55.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by MartinWeindel**
**How to categorize this PR?**

/area control-plane
/area control-plane-migration
/kind enhancement

**What this PR does / why we need it**:
The `DNSEntries` of the shoot must be stored in the `.status.state` of the `Extension` resource for resurrection after control plane migration.
If a shoot has about 2000 entries, this state becomes so big, that the request size limit of etcd (1.5MB) is hit (`etcdserver: request is too large`).
To shift the maximum number of DNS entries which can be supported, the state is now compressed with the `brotli` algorithm. We expect to see compression ratios >= 6, so the limit should now be beyond 10,000 entries.

**Which issue(s) this PR fixes**:
Fixes #413 

**Special notes for your reviewer**:

**Release note**:

```noteworthy operator
The entry list stored in the extension resource status is now compressed to shift the limit before hitting the request size limit of etcd. 
```

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -135,8 +135,12 @@ test-cov:
...
+test-integration-lifecycle: $(REPORT_COLLECTOR) $(SETUP_ENVTEST)
+	@bash $(GARDENER_HACK_DIR)/test-integration.sh ./test/integration/lifecycle/...
+
 .PHONY: verify
-verify: check format test sast
+verify: check format test test-integration-lifecycle sast
 
 .PHONY: verify-extended
-verify-extended: check-generate check format test-cov test-clean sast-report
+verify-extended: check-generate check format test-cov test-clean test-integration-lifecycle sast-report
```
Comment (marc1404) [inline Makefile:146]: While the make target only runs the lifecycle integration test today shouldn't we name it `test-integration` instead so it can be the generic entry point for all integration tests?

File: pkg/controller/common/state.go [hunk 2]
```diff
@@ -184,11 +212,16 @@ func (s *StateHandler) Update(reason string) error {
...
 		}
-		s.ext.Status.State.Raw, err = json.Marshal(wire)
+		data, err := json.Marshal(wire)
 		if err != nil {
 			s.Info("marshalling failed", "error", err)
 			return err
 		}
+		s.ext.Status.State.Raw, err = CompressEntriesState(data)
+		if err != nil {
+			s.Info("compressing failed", "error", err)
```
Comment (marc1404) [inline pkg/controller/common/state.go:222]: Nit: What about using `s.Error()` instead?
```suggestion
			s.Error(err, "compressing failed")
```

File: test/integration/lifecycle/state_test.go [hunk 3]
```diff
@@ -0,0 +1,326 @@
...
+			Spec: extensionsv1alpha1.ExtensionSpec{
+				DefaultSpec: extensionsv1alpha1.DefaultSpec{
+					Type: "shoot-dns-service",
+				},
+			},
+		}
+		Expect(c.Create(ctx, ext)).To(Succeed())
+
+		By("wait for 'external' DNSProvider and patch it to Ready")
+		CEventually(ctx, func(g Gomega) error {
```
Comment (marc1404) [inline test/integration/lifecycle/state_test.go:206]: Out of curiosity: What is `CEventually` in gomega? I can only find the regular [`Eventually`](https://pkg.go.dev/github.com/onsi/gomega#Eventually) in the documentation and that also allows to pass the context as the first argument.

File: pkg/controller/common/compressedstate.go
Comment (marc1404) [inline pkg/controller/common/compressedstate.go:1]: I know you covered the entire extension state logic through the integration tests.
However, I think the functions in this file are well-suited to be covered through unit tests. What do you think?

**Review by marc1404 — COMMENTED** [review]
Great work!
I'm excited to have this extension state compression in so that the control plane migration problem would only occur in much larger workloads.

File: Makefile (hunk 1 above)
Comment (MartinWeindel) [reply Makefile:146]: The problem is the `test/integration/healthcheck` test which is expected to run in a Gardener test env.
So we have two different kinds of integration tests here.

File: test/integration/lifecycle/state_test.go (hunk 3 above)
Comment (MartinWeindel) [reply test/integration/lifecycle/state_test.go:206]: CEventually is like gomega.Eventually but with a context.
It's a gardener util method: See https://github.com/gardener/gardener/blob/master/pkg/utils/test/test.go#L283

**Review by marc1404 — APPROVED** [review]
/lgtm

Thank you!
